//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 申请 的本地化字符串。
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量增加 的本地化字符串。
        /// </summary>
        internal static string BtnBatch {
            get {
                return ResourceManager.GetString("BtnBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 班级分组 的本地化字符串。
        /// </summary>
        internal static string BtnClassGroup {
            get {
                return ResourceManager.GetString("BtnClassGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 清空数据 的本地化字符串。
        /// </summary>
        internal static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string BtnComplete {
            get {
                return ResourceManager.GetString("BtnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下载 的本地化字符串。
        /// </summary>
        internal static string BtnDown {
            get {
                return ResourceManager.GetString("BtnDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出班级到Excel 的本地化字符串。
        /// </summary>
        internal static string BtnExportClassToExcel {
            get {
                return ResourceManager.GetString("BtnExportClassToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出教学班和学生 的本地化字符串。
        /// </summary>
        internal static string BtnExportOrgAndStudent {
            get {
                return ResourceManager.GetString("BtnExportOrgAndStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出学生到Excel 的本地化字符串。
        /// </summary>
        internal static string BtnExportStudentToExcel {
            get {
                return ResourceManager.GetString("BtnExportStudentToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出到Excel 的本地化字符串。
        /// </summary>
        internal static string BtnExportToExcel {
            get {
                return ResourceManager.GetString("BtnExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出到Pdf 的本地化字符串。
        /// </summary>
        internal static string BtnExportToPdf {
            get {
                return ResourceManager.GetString("BtnExportToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出到Word 的本地化字符串。
        /// </summary>
        internal static string BtnExportToWord {
            get {
                return ResourceManager.GetString("BtnExportToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string BtnImport {
            get {
                return ResourceManager.GetString("BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 从Excel导入班级 的本地化字符串。
        /// </summary>
        internal static string BtnImportClassFromExcel {
            get {
                return ResourceManager.GetString("BtnImportClassFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 从Excel导入 的本地化字符串。
        /// </summary>
        internal static string BtnImportFromExcel {
            get {
                return ResourceManager.GetString("BtnImportFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 从Excel导入学生 的本地化字符串。
        /// </summary>
        internal static string BtnImportStudentFromExcel {
            get {
                return ResourceManager.GetString("BtnImportStudentFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导入学生照片 的本地化字符串。
        /// </summary>
        internal static string BtnImportStudentPhoto {
            get {
                return ResourceManager.GetString("BtnImportStudentPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更多 的本地化字符串。
        /// </summary>
        internal static string BtnMore {
            get {
                return ResourceManager.GetString("BtnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下一步 的本地化字符串。
        /// </summary>
        internal static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更多 的本地化字符串。
        /// </summary>
        internal static string BtnOther {
            get {
                return ResourceManager.GetString("BtnOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上一步 的本地化字符串。
        /// </summary>
        internal static string BtnPrevious {
            get {
                return ResourceManager.GetString("BtnPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 打印 的本地化字符串。
        /// </summary>
        internal static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string BtnReturn {
            get {
                return ResourceManager.GetString("BtnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 报废 的本地化字符串。
        /// </summary>
        internal static string BtnScrap {
            get {
                return ResourceManager.GetString("BtnScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string BtnSelect {
            get {
                return ResourceManager.GetString("BtnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string BtnSet {
            get {
                return ResourceManager.GetString("BtnSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 表单类型 的本地化字符串。
        /// </summary>
        internal static string FormTypeTitle {
            get {
                return ResourceManager.GetString("FormTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作成功! 的本地化字符串。
        /// </summary>
        internal static string MsgActionOk {
            get {
                return ResourceManager.GetString("MsgActionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定要删除所选? 的本地化字符串。
        /// </summary>
        internal static string MsgDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除失败! 的本地化字符串。
        /// </summary>
        internal static string MsgDeleteFail {
            get {
                return ResourceManager.GetString("MsgDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功! 的本地化字符串。
        /// </summary>
        internal static string MsgDeleteOk {
            get {
                return ResourceManager.GetString("MsgDeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统错误! 的本地化字符串。
        /// </summary>
        internal static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记录不存在! 的本地化字符串。
        /// </summary>
        internal static string MsgNotFound {
            get {
                return ResourceManager.GetString("MsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先勾选需要删除的项目! 的本地化字符串。
        /// </summary>
        internal static string MsgNotSelect {
            get {
                return ResourceManager.GetString("MsgNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记录已过时! 的本地化字符串。
        /// </summary>
        internal static string MsgObsolete {
            get {
                return ResourceManager.GetString("MsgObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交失败! 的本地化字符串。
        /// </summary>
        internal static string MsgSaveFail {
            get {
                return ResourceManager.GetString("MsgSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交成功! 的本地化字符串。
        /// </summary>
        internal static string MsgSaveOk {
            get {
                return ResourceManager.GetString("MsgSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 没有查询到对应SchoolCode的相关用户信息! 的本地化字符串。
        /// </summary>
        internal static string MsgSchoolCode {
            get {
                return ResourceManager.GetString("MsgSchoolCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string TipPleaseSelect {
            get {
                return ResourceManager.GetString("TipPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入查询内容 的本地化字符串。
        /// </summary>
        internal static string TipSearch {
            get {
                return ResourceManager.GetString("TipSearch", resourceCulture);
            }
        }
    }
}
