//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XkSystem.KVSMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zytx.vabd.sztelecom.com", ConfigurationName="KVSMSService.SMSService")]
    public interface SMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SendMessageReturn")]
        string SendMessage(string uc, string pw, string userid, string rand, string callee, string message, string sendtime, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SendMessageReturn")]
        System.Threading.Tasks.Task<string> SendMessageAsync(string uc, string pw, string userid, string rand, string callee, string message, string sendtime, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sendMsgsReturn")]
        string sendMsgs(string uc, string pw, string userid, string rand, string callee, string message, string sendtime, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sendMsgsReturn")]
        System.Threading.Tasks.Task<string> sendMsgsAsync(string uc, string pw, string userid, string rand, string callee, string message, string sendtime, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRandomReturn")]
        string getRandom();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRandomReturn")]
        System.Threading.Tasks.Task<string> getRandomAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServiceChannel : XkSystem.KVSMSService.SMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceClient : System.ServiceModel.ClientBase<XkSystem.KVSMSService.SMSService>, XkSystem.KVSMSService.SMSService {
        
        public SMSServiceClient() {
        }
        
        public SMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendMessage(string uc, string pw, string userid, string rand, string callee, string message, string sendtime, string msgid) {
            return base.Channel.SendMessage(uc, pw, userid, rand, callee, message, sendtime, msgid);
        }
        
        public System.Threading.Tasks.Task<string> SendMessageAsync(string uc, string pw, string userid, string rand, string callee, string message, string sendtime, string msgid) {
            return base.Channel.SendMessageAsync(uc, pw, userid, rand, callee, message, sendtime, msgid);
        }
        
        public string sendMsgs(string uc, string pw, string userid, string rand, string callee, string message, string sendtime, string msgid) {
            return base.Channel.sendMsgs(uc, pw, userid, rand, callee, message, sendtime, msgid);
        }
        
        public System.Threading.Tasks.Task<string> sendMsgsAsync(string uc, string pw, string userid, string rand, string callee, string message, string sendtime, string msgid) {
            return base.Channel.sendMsgsAsync(uc, pw, userid, rand, callee, message, sendtime, msgid);
        }
        
        public string getRandom() {
            return base.Channel.getRandom();
        }
        
        public System.Threading.Tasks.Task<string> getRandomAsync() {
            return base.Channel.getRandomAsync();
        }
    }
}
